apiVersion: batch/v1
kind: Job
metadata:
  name: load-generator
  namespace: scaling-lab
spec:
  activeDeadlineSeconds: 180
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      restartPolicy: Never
      automountServiceAccountToken: false
      containers:
        - name: client
          image: akstraining555a1e03.azurecr.io/scaling/load:1.0.0
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop: [ALL]
          env:
            - name: TARGET_URL
              value: http://cpu-web/work
            - name: DURATION_SECONDS
              value: "120"
            - name: CONCURRENCY
              value: "2"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi