apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cpu-web
  namespace: scaling-lab
spec:
  minAvailable: 2
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: cpu-web