import { fileURLToPath } from 'node:url';

const lab = process.env.LAB_DIR || fileURLToPath(new URL('../../labs/01-scaling', import.meta.url));
const base = ['--context=lab', '--namespace=scaling-lab', '--request-timeout=20s'];
export const kubectl = (...args) => ({ file: 'kubectl', args: [...base, ...args] });
const apply = (...files) => kubectl('apply', ...files.flatMap(file => ['-f', `${lab}/${file}.yaml`]));
const rollout = name => kubectl('rollout', 'status', `deployment/${name}`, '--timeout=60s');
const stopLoad = kubectl('delete', 'job', 'load-generator', '--ignore-not-found', '--wait=true');
const stopHpa = kubectl('delete', 'hpa', 'cpu-web', '--ignore-not-found');
export const actions = [
  { id: 'inspect', phase: 'HPA', label: 'Inspect workloads', description: 'Read the lab pods, Deployments, autoscaler, and disruption budget. No resources are changed.', expected: 'The current replica counts, readiness, and autoscaler targets appear in the terminal.', steps: [kubectl('get', 'deployments,hpa,pdb,pods', '-o', 'wide')] },
  { id: 'web', phase: 'HPA', label: 'Deploy web + HPA', mutation: true, description: 'Create two CPU-work pods and a CPU-based HPA. Reapplying this baseline resets the declared replicas to two.', expected: 'Two Ready web pods; CPU target 50% of the 100m request, with a maximum of four replicas.', steps: [apply('web'), rollout('cpu-web'), apply('hpa'), kubectl('get', 'hpa')] },
  { id: 'load', phase: 'HPA', label: 'Start two-minute load', mutation: true, description: 'Replace the previous load Job and send concurrent CPU-work requests through the Service. New connections let requests reach different pods.', expected: 'CPU increases and HPA scales above two replicas, up to four. Wait for metrics and startup delays.', steps: [stopLoad, apply('load')] },
  { id: 'hpa-watch', phase: 'HPA', label: 'Watch HPA', description: 'Stream HPA updates for up to 45 seconds. Stopping this watch does not stop the load Job.', expected: 'The CPU target and current replica count change as the controller reacts.', steps: [{ ...kubectl('get', 'hpa', 'cpu-web', '--watch'), watch: true }] },
  { id: 'load-logs', phase: 'HPA', label: 'Show request distribution', description: 'Read the load generator summaries, including successful requests, latency, and counts by serving pod.', expected: 'The servedBy map gains pod names as requests reach new replicas.', steps: [kubectl('logs', 'job/load-generator', '--tail=15')] },
  { id: 'metrics', phase: 'HPA', label: 'Inspect CPU + decisions', description: 'Read pod CPU/memory usage and the HPA controller conditions and events.', expected: 'CPU utilization is relative to requests, not limits. SuccessfulRescale events explain replica changes.', steps: [kubectl('top', 'pods'), kubectl('describe', 'hpa', 'cpu-web')] },
  { id: 'stop-load', phase: 'HPA', label: 'Stop load', mutation: true, description: 'Delete only the load-generator Job. The HPA stays active and can scale down.', expected: 'CPU falls and replicas return to two after the 60-second stabilization window and controller delays.', steps: [stopLoad, kubectl('get', 'hpa')] },
  { id: 'pdb', phase: 'PDB', label: 'Prepare two-pod budget', mutation: true, description: 'Stop load and remove the HPA, set two web replicas, then require at least two available pods. Deploy the web baseline first.', expected: 'Two Ready pods and zero allowed disruptions. A healthy pod cannot be evicted.', steps: [stopLoad, stopHpa, kubectl('scale', 'deployment/cpu-web', '--replicas=2'), rollout('cpu-web'), apply('pdb'), kubectl('wait', '--for=jsonpath={.status.disruptionsAllowed}=0', 'pdb/cpu-web', '--timeout=60s'), kubectl('get', 'pdb')] },
  { id: 'evict', phase: 'PDB', label: 'Request pod eviction', mutation: true, description: 'Select a Ready cpu-web pod and submit a policy/v1 Eviction. This is not direct pod deletion and does not drain a node.', expected: 'At two healthy pods: a 429 PDB rejection. At three: accepted eviction followed by a replacement pod.', eviction: true, steps: [kubectl('get', 'pods', '-l', 'app=cpu-web', '-o', 'json')] },
  { id: 'third-pod', phase: 'PDB', label: 'Add eviction headroom', mutation: true, description: 'Set three web replicas while the HPA is absent, then wait for one allowed disruption. Run the PDB preparation first.', expected: 'Three Ready pods and one allowed disruption. Run Request pod eviction again.', steps: [stopHpa, kubectl('scale', 'deployment/cpu-web', '--replicas=3'), rollout('cpu-web'), kubectl('wait', '--for=jsonpath={.status.disruptionsAllowed}=1', 'pdb/cpu-web', '--timeout=60s'), kubectl('get', 'pdb')] },
  { id: 'pods-watch', phase: 'PDB', label: 'Watch pod replacement', description: 'Stream pod lifecycle changes for up to 45 seconds.', expected: 'The Deployment restores its desired replica count after an accepted eviction. The PDB does not create pods.', steps: [{ ...kubectl('get', 'pods', '-l', 'app=cpu-web', '-o', 'wide', '--watch'), watch: true }] },
  { id: 'queue', phase: 'KEDA', label: 'Prepare queue + workers', mutation: true, description: 'Remove the web exercise and create disposable Redis plus a zero-replica worker. Do not rerun while queue processing is active.', expected: 'Redis is Ready and the worker Deployment is at zero. No KEDA add-on is installed by this action.', steps: [stopLoad, stopHpa, kubectl('delete', '-f', `${lab}/pdb.yaml`, '-f', `${lab}/web.yaml`, '--ignore-not-found', '--wait=true'), apply('queue'), rollout('redis')] },
  { id: 'scaledobject', phase: 'KEDA', label: 'Apply queue scaler', mutation: true, description: 'Create the Redis ScaledObject. The cluster owner must have separately enabled managed KEDA; this action cannot enable add-ons.', expected: 'ScaledObject Ready and generated HPA keda-hpa-queue-worker. A missing CRD means KEDA setup is still required.', steps: [apply('scaledobject'), kubectl('wait', '--for=condition=Ready', 'scaledobject/queue-worker', '--timeout=60s'), kubectl('get', 'scaledobjects,hpa')] },
  { id: 'seed', phase: 'KEDA', label: 'Enqueue 200 jobs', mutation: true, description: 'Push 200 uniquely named synthetic jobs to Redis. Each worker processes one job at a time, taking two seconds per job.', expected: 'The queue wakes workers from zero, then the generated HPA scales up to four.', steps: [{ file: 'node', args: ['queue.mjs', 'seed', '200'] }] },
  { id: 'queue-status', phase: 'KEDA', label: 'Inspect queue counts', description: 'Read waiting, processing, and completed counters. An empty waiting list does not mean all work is finished.', expected: 'Waiting falls, processing reflects in-flight jobs, and completed rises.', steps: [{ file: 'node', args: ['queue.mjs', 'status'] }] },
  { id: 'worker-logs', phase: 'KEDA', label: 'Read worker activity', description: 'Read recent job_started and job_completed events across current worker pods.', expected: 'Each event includes the worker pod and job ID. No worker pods is normal after scale-to-zero.', steps: [kubectl('logs', '-l', 'app=queue-worker', '--prefix=true', '--tail=10', '--max-log-requests=4')] },
  { id: 'workers-watch', phase: 'KEDA', label: 'Watch worker replicas', description: 'Stream the worker Deployment for up to 45 seconds. Repeat the watch to observe cooldown.', expected: 'Workers activate, scale out, then return to zero after queue inactivity and the 60-second cooldown.', steps: [{ ...kubectl('get', 'deployment', 'queue-worker', '--watch'), watch: true }] },
  { id: 'events', phase: 'Diagnostics', label: 'Read lab events', description: 'Read events only in scaling-lab, ordered by creation time.', expected: 'Scheduling, image pull, scale, and readiness events help explain unexpected behavior.', steps: [kubectl('get', 'events', '--sort-by=.metadata.creationTimestamp')] },
];

export function displayCommand(step) {
  return [step.file, ...step.args].map(part => /^[a-zA-Z0-9_./:=,@-]+$/.test(part) ? part : JSON.stringify(part)).join(' ');
}

export function publicActions() {
  return actions.map(({ steps, eviction, ...action }) => ({
    ...action, commands: steps.map(displayCommand).concat(eviction ? ['kubectl --context=lab --namespace=scaling-lab create --raw=/api/v1/namespaces/scaling-lab/pods/<ready-pod>/eviction -f -'] : []),
  }));
}