apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-queue-workload
  namespace: keda-lab
  annotations:
    azure.workload.identity/client-id: 6c941ddf-3965-48b5-963f-8f5a5ffdb1a4
    azure.workload.identity/tenant-id: 45b68ab1-2c84-414f-918d-e945e189121d
automountServiceAccountToken: false